# Generated by Django 4.0.5 on 2022-06-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lite', '0002_editor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
